import AboutUs from "@/components/aboutus";
import MasterHead from "@/components/masterHead";
import Skills from "@/components/skills";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nidus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MasterHead />
      <AboutUs />
      <Skills />
    </div>
  );
}