import Head from "next/head";

const privacy = () => {
  return (
    <>
      <Head>
        <title>Nidus - Políticas de Privacidade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default privacy;