
import Head from "next/head";
import Image from "next/image";

const privacy = () => {
  return (
    <div>
      <Head>
        <title>Nidus - Políticas de Privacidade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="legal-info min-h-screen bg-black text-white">
        <div className="pl-10 pt-10 mb-8">
          <Image
            src={"/assets/logo-img.png"}
            alt="Logo"
            width={100}
            height={100}
          />
        </div>

        <div className="container mx-auto leading-5 px-10 lg:px-32">
          <h1 className="font-bold text-xl lg:text-2xl text-center">
            Informações de Privacidade para Usuários do Website
          </h1>

          <div className="text-center">
            <div>by</div>
            <div className="font-bold">Nidus Solutions</div>
          </div>

          <article className="text-lg mt-10">
            <p>
              As seguintes informações têm como objetivo esclarecer o tipo, a
              extensão e a finalidade da coleta e uso de dados pessoais e
              informar sobre seus direitos em relação à coleta e processamento
              dos seus dados pessoais. Essas informações são fornecidas de
              acordo com os Artigos 13 e 14 da Lei Geral de Proteção de Dados{" "}
              <strong>("LGPD")</strong>.
            </p>

            <p>
              Essas informações de privacidade são direcionadas a (i) usuários
              do website "nidussolutions.com" e (ii) parceiros de negócios e
              clientes, incluindo seus funcionários.
            </p>

            <section>
              <h2 className="font-bold mt-4">1. Quem é responsável por todas as atividades de processamento e quem é o seu contato em caso de dúvidas?</h2>
              <p>
                O controlador de todas as atividades de processamento é:
                <div className="ml-4">
                  Nidus Solutions Ltda
                  <br />
                  CNPJ: 12.345.678/0001-90
                  <br />
                  Rua da Faesa, 71
                  <br />
                  São Pedro - Vitória/ES
                  <br />
                  <a href="mailto:ola@nidussolutions.com">ola@nidussolutions.com</a>
                </div>
              </p>
            </section>

            <section>
              <h2 className="font-bold mt-4">2. Quais dados estamos processando e de onde eles vêm?</h2>
              <p>Se você é um usuário do website:</p>
              <p>
                Ao usar o website, cookies são utilizados. Para mais informações, consulte a seção 6.
                Se você nos contatar através do formulário de contato online na seção "Fale Conosco" ou por outras opções de contato oferecidas, os dados pessoais fornecidos serão processados para poder lidar e responder à sua consulta, em particular seu nome, sobrenome, endereço de e-mail, número de telefone e quaisquer dados especificados no texto.
              </p>
              <p>Se você é um parceiro de negócios/cliente:</p>
              <p>
                Com base em uma relação (pré-)contratual, os dados pessoais fornecidos por você durante a iniciação da relação contratual, bem como os dados fornecidos durante a relação contratual em vigor, serão processados:
              </p>
              <ul className="list-disc list-inside ml-4">
                <li>Nome, empresa ou nome comercial;</li>
                <li>Endereço;</li>
                <li>Dados de contato (telefone, e-mail, fax);</li>
                <li>Dados do CNPJ;</li>
                <li>Dados da conta bancária;</li>
                <li>Informações do cartão de crédito;</li>
                <li>Nomes de pessoas de contato;</li>
                <li>Dados de contato das pessoas de contato (telefone, e-mail, fax, endereço, etc.);</li>
                <li>Textos de contratos e correspondência comercial.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-bold mt-4">3. Como estamos processando seus dados pessoais e para quais finalidades?</h2>
              <p>Processamos seus dados pessoais para diferentes finalidades e por vários meios, dependendo se você é (i) um visitante do nosso website ou (ii) um parceiro de negócios/cliente.</p>
              <p>Se você é um usuário do website:</p>
              <ul className="list-disc list-inside ml-4">
                <li>
                  Para o cumprimento de obrigações (pré-)contratuais (Artigo 6, parágrafo 1, lit. b LGPD): Processamos os dados coletados de você para o propósito de contatá-lo ou correspondência com você por escrito, eletronicamente ou por telefone, incluindo no contexto de relações (pré-)contratuais. Sem esses dados, não podemos cumprir o contrato com você.
                </li>
                <li>
                  Para o cumprimento de obrigações legais (Artigo 6, parágrafo 1, lit. c LGPD): Seus dados também são processados para o propósito de cumprir várias obrigações legais, como fornecer informações para autoridades policiais e tribunais em caso de um incidente.
                </li>
                <li>
                  Com base em interesses legítimos (Artigo 6, parágrafo 1, lit. f LGPD): Processamos dados pessoais para proteger nossos interesses legítimos, a menos que seus interesses de confidencialidade prevaleçam. Nossos interesses legítimos incluem processar e responder suas consultas, iniciar contatos comerciais e garantir a segurança da operação do website. Você pode se opor ao processamento de seus dados para fins de publicidade a qualquer momento (para mais informações sobre Cookies e Ferramentas de Análise, consulte a Seção 6).
                </li>
              </ul>
              <p>Se você é um parceiro de negócios/cliente:</p>
              <ul className="list-disc list-inside ml-4">
                <li>
                  Para o cumprimento de obrigações (pré-)contratuais (Artigo 6, parágrafo 1, lit. b LGPD): O objetivo do processamento de dados pessoais é o desempenho de nossos deveres (pré-)contratuais de acordo com nossa relação contratual com você, como nossos deveres de proteção, diligência e esclarecimento, a prestação de serviços, bem como a liquidação de reivindicações decorrentes do contrato, faturamento, etc. Sem esses dados, não podemos cumprir o contrato com você.
                </li>
                <li>
                  Para o cumprimento de obrigações legais (Artigo 6, parágrafo 1, lit. c LGPD): Dados pessoais também são processados para o cumprimento de várias obrigações legais, como a obrigação de manter uma contabilidade adequada ou fornecer informações para autoridades policiais e tribunais em caso de um incidente.
                </li>
                <li>
                  Com base em interesses legítimos (Artigo 6, parágrafo 1, lit. f LGPD): Processamos dados pessoais para proteger nossos interesses legítimos, a menos que seus interesses de confidencialidade prevaleçam. Esses interesses legítimos incluem, por exemplo, o interesse em otimizar nossa oferta, o interesse em enviar publicidade sobre nossos produtos e serviços, contatá-lo a respeito da iniciação ou processamento de outras relações contratuais, e o interesse na disponibilidade dos dados em caso de disputa legal. Você pode se opor ao processamento de dados pessoais para fins de publicidade a qualquer momento.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-bold mt-4">4. Transferência dos seus dados</h2>
              <p>
                Transferiremos seus dados pessoais se estivermos legalmente obrigados a fazê-lo para as seguintes autoridades e instituições:
              </p>
              <p>Se você é um usuário do website:</p>
              <ul className="list-disc list-inside ml-4">
                <li>Provedores de Serviços (Provedores de TI);</li>
                <li>Tribunais e autoridades em caso de necessidade;</li>
                <li>Representantes legais ou advogados e terceiros que auxiliam em serviços jurídicos.</li>
              </ul>
              <p>Se você é um parceiro de negócios/cliente:</p>
              <ul className="list-disc list-inside ml-4">
                <li>Provedores de Serviços (Provedores de TI);</li>
                <li>Tribunais e autoridades em caso de necessidade;</li>
                <li>Representantes legais ou advogados e terceiros que auxiliam em serviços jurídicos;</li>
                <li>Bancos;</li>
                <li>Consultores fiscais e contadores;</li>
                <li>Auditores;</li>
                <li>Seguradoras em caso de incidente.</li>
              </ul>
              <p>
                Garantiremos que seus dados pessoais sejam transferidos com base em Cláusulas Contratuais Padrão (atualmente: [EU] 2021/914) ou de outra forma de acordo com os Artigos 46, 47 ou 49 LGPD, se os destinatários mencionados de seus dados pessoais estiverem localizados fora do EEE e

                se a Comissão Europeia não tiver decidido que há um nível adequado de proteção de dados no país onde o destinatário dos seus dados pessoais está localizado.
              </p>
              <p>
                Além disso, os provedores de serviços (processadores) receberão seus dados pessoais para prestar seus respectivos serviços (por exemplo, provedores de serviços de TI). Todos os provedores de serviços são contratualmente obrigados a manter seus dados pessoais confidenciais e podem usar seus dados pessoais apenas em nosso nome e conforme nossas instruções.
              </p>
            </section>

            <section>
              <h2 className="font-bold mt-4">5. Duração do processamento/período de armazenamento</h2>
              <p>
                Processaremos seus dados pessoais enquanto o processamento for necessário. Seus dados pessoais serão anonimizados ou apagados automaticamente assim que o processamento não for mais necessário.
              </p>
              <p>
                Reteremos seus dados pessoais necessários para a execução de nossos serviços de acordo com as obrigações legais de retenção e documentação (por exemplo, de acordo com o Código Comercial Brasileiro ou o Código Tributário Nacional). Além disso, cumprimos os prazos legais de prescrição, por exemplo, de acordo com o Código Civil Brasileiro. Esses períodos de prescrição podem durar até 30 anos em certos casos.
              </p>
            </section>

            <section>
              <h2 className="font-bold mt-4">6. Processamento de dados em conexão com o website</h2>
              <p><strong>Cookies e Ferramentas de Análise</strong></p>
              <p>
                Nosso website utiliza cookies que são absolutamente necessários para a estrutura ou funcionamento do website (cookies tecnicamente necessários). Esses cookies não podem ser desativados.
              </p>
              <p>
                Cookies são pequenos arquivos de texto que são temporariamente armazenados no seu dispositivo com a ajuda do navegador e/ou que o seu navegador salva. Eles não causam nenhum dano, mas tornam o uso do website mais amigável. Os cookies são deletados quando você fecha o navegador e não permanecem armazenados no seu computador. Não utilizamos "cookies persistentes".
              </p>
              <p>
                O período de armazenamento dos respectivos cookies depende da duração da respectiva sessão da plataforma.
              </p>
              <p>
                Estamos utilizando o serviço de análise web "Fathom Analytics" com base em nossos interesses legítimos (Artigo 6, parágrafo 1, lit. f LGPD) para otimizar continuamente nossa oferta, tanto tecnicamente quanto em termos de conteúdo. Fathom Analytics é uma marca da Conva Ventures Inc. BOX 37058 Millstream PO, Victoria, BC, V9B 0E8, Canadá ("Fathom").
              </p>
              <p>
                Você pode encontrar mais informações sobre a implementação técnica aqui:{" "}
                <a href="https://usefathom.com/blog/anonymization" target="_blank" rel="noopener noreferrer">
                  usefathom.com/blog/anonymization
                </a>.
              </p>
              <p>
                Mais informações sobre proteção de dados no Fathom podem ser encontradas em{" "}
                <a href="https://usefathom.com/data" target="_blank" rel="noopener noreferrer">
                  usefathom.com/data
                </a>.
              </p>
            </section>

            <section>
              <h2 className="font-bold mt-4">7. Quais são seus direitos em relação aos seus dados pessoais?</h2>
              <p><strong>Direito à informação:</strong> Desde que processemos seus dados pessoais, você tem o direito de obter informações sobre as finalidades do processamento, as categorias de dados pessoais, os destinatários dos seus dados pessoais, a duração do armazenamento, seus direitos, a origem dos seus dados pessoais e a existência de uma tomada de decisão automatizada.</p>
              <p><strong>Retificação e apagamento de dados:</strong> Se processarmos dados pessoais imprecisos ou incompletos, você tem o direito de retificação desses dados. Você também pode solicitar o apagamento dos seus dados pessoais se seus dados forem processados de maneira ilegal, sujeitando-se a obrigações legais que impeçam o apagamento dos seus dados pessoais.</p>
              <p><strong>Restrição do processamento:</strong> Você pode solicitar a restrição do processamento dos seus dados pessoais em certos casos.</p>
              <p><strong>Portabilidade de dados:</strong> Você tem o direito de receber os dados pessoais que nos forneceu em um formato estruturado, comumente usado e legível por máquina. Você tem o direito de transmissão direta desses dados para outro controlador, na medida em que isso seja tecnicamente viável.</p>
              <p><strong>Direito de objeção:</strong> Você tem o direito de se opor, com base em sua situação particular, a qualquer momento ao processamento de dados pessoais que lhe dizem respeito. Se você se opuser ao processamento de seus dados pessoais, cessaremos o processamento de seus dados pessoais, a menos que nossos interesses legítimos em processar seus dados pessoais prevaleçam sobre os seus interesses.</p>
              <p><strong>Reclamação:</strong> Você tem o direito de apresentar uma reclamação à autoridade supervisora se acreditar que o processamento de seus dados viola a lei de proteção de dados ou seus direitos à proteção dos seus dados pessoais foram infringidos. No Brasil, esta é a Autoridade Nacional de Proteção de Dados (ANPD).</p>
            </section>

            <section>
              <h2 className="font-bold mt-4">8. Contato</h2>
              <p>
                Para exercer seus direitos em relação aos seus dados pessoais processados por nós, por favor entre em contato com:
                <div className="ml-4">
                  Nidus Solutions Ltda
                  <br />
                  CNPJ: 12.345.678/0001-90
                  <br />
                  Rua da Faesa, 71
                  <br />
                  São Pedro - Vitória/ES
                  <br />
                  <a href="mailto:ola@nidussolutions.com">ola@nidussolutions.com</a>
                </div>
              </p>
            </section>

            <section>
              <h2 className="font-bold mt-4">9. Definições</h2>
              <p>
                As definições dos termos utilizados (por exemplo, "dados pessoais" ou "processamento") podem ser encontradas no Artigo 4º da LGPD.
              </p>
            </section>
          </article>
        </div>
      </div>
    </div>
  );
};

export default privacy;